"""Added artist name field to User

Revision ID: f86ba987b2fa
Revises: 6a16467fd360
Create Date: 2024-12-01 16:52:14.260219

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f86ba987b2fa'
down_revision = '6a16467fd360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'artist_name')
    # ### end Alembic commands ###
