name: Run Backend Tests

on:
  push:
    branches:
      - IntegrationTests
  pull_request:
    branches:
      - IntegrationTests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      # 3. Instala Poetry
      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      # 4. Instala las dependencias del backend
      - name: Install dependencies
        working-directory: ./backend
        run: |
          poetry install

      # 5. Crear el archivo .env con las variables necesarias
      - name: Set up environment variables
        run: |
          echo "PROJECT_NAME=mt_app" >> .env
          echo "FIRST_SUPERUSER=Melotunes" >> .env
          echo "FIRST_SUPERUSER_PASSWORD=Melotunes123" >> .env
          echo "BACKEND_CORS_ORIGINS=http://localhost:8080" >> .env
          echo "DATABASE_URL=sqlite:///./mt_db.sqlite" >> .env

      # 6. Ejecuta las migraciones de Alembic
      - name: Run Alembic migrations
        working-directory: ./backend
        run: |
          poetry run alembic upgrade head

      # 7. Instala pytest-cov
      - name: Install pytest-cov
        working-directory: ./backend
        run: |
          poetry add pytest-cov

      # 8. Ejecuta los tests con cobertura
      - name: Run tests with coverage
        working-directory: ./backend
        run: |
          poetry run pytest --disable-warnings --cov=./ --cov-report=xml

      # 9. Sube el reporte de cobertura (opcional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./backend/coverage.xml