name: Run Backend Tests

on:
  push:
    branches:
      - Integration_Tests  # Ejecuta los tests en cada commit a la rama Integration_Tests
  pull_request:
    branches:
      - Integration_Tests  # También en cada PR hacia la rama Integration_Tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      # 3. Instala Poetry
      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      # 4. Instala las dependencias del backend
      - name: Install dependencies
        working-directory: ./backend
        run: |
          poetry install

      # 5. Ejecuta las migraciones de Alembic
      - name: Run Alembic migrations
        working-directory: ./backend
        run: |
          poetry run alembic upgrade head

      # 6. Ejecuta los tests con pytest, configurando las variables de entorno necesarias
      - name: Run tests
        working-directory: ./backend
        env:
          PROJECT_NAME: mt_app
          FIRST_SUPERUSER: Melotunes
          FIRST_SUPERUSER_PASSWORD: Melotunes123
          BACKEND_CORS_ORIGINS: http://localhost:8080
          DATABASE_URL: sqlite:///./mt_db.sqlite  # Establece la URL de la base de datos (SQLite en este caso)
        run: |
          poetry run pytest --disable-warnings
